[tool.isort]
multi_line_output = 3
include_trailing_comma = true


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "project.settings_file"
addopts = "--tb=native -cov-report=term-missing -v"
python_files = "*_tests.py"
